### ISSUE TITLE
How can I make this load the newest autosave?

### ISSUE THREAD

**Issue by CSchank** [zoltantamasvajda/openttd-server#1]
I installed this, but every time I restart the server it regenerates the map. Is there an easy way to make it load the last autosave instead? Also, does this autosave when you call `sudo snap stop openttd-server`?

**Comment by zoltantamasvajda** [comment]
Admittedly managing save games is not the most convenient thing with the snap right now but it is by all means not impossible. Here's how to do it:

### First you need to enable admin password for the server:
`sudo snap stop openttd-server`

### Next you need to edit the configuration file:
`sudo sed -i 's/^rcon_password .*$/rcon_password = yourpassword/' /root/snap/openttd-server/current/.config/openttd/openttd.cfg`

Replace `yourpassword` with a password of your choice

Alternatively you can edit the config file at `/root/snap/openttd-server/current/.config/openttd/openttd.cfg` manually with a text editor of your choice and change any settings you'd like. (you _will_ need to run the text editor as _root_ for this to work e.g.: `sudo gedit /root/snap/openttd-server/current/.config/openttd/openttd.cfg`)

https://wiki.openttd.org/en/Archive/Manual/Settings/Openttd.cfg

### Lastly restart the server:
`sudo snap start openttd-server`

Now you have the option to control the server using to rcon:
https://wiki.openttd.org/en/Manual/Dedicated%20server#controlling-the-server-with-rcon
https://wiki.openttd.org/en/Manual/Console

For future versions I'll look into implementing some custom commands to simplify this.

**Comment by zoltantamasvajda** [comment]
I am in the process of releasing a new version which will solve this issue. You can check the README file for more details 
but the tldr is:
- rcon password can now be set using `sudo snap set openttd-server rcon-password=password`
- The package will now by default auto load the last savegame. This behavior can be changed using `sudo snap set openttd-server loadgame={last-autosave | false | filename.sav}`

**Comment by CSchank** [comment]
Fantastic, thank you! Having it load the last autosave by default will already make this method of installing the server very valuable, especially for new server admins. Have you advertised this on the forums?
