### ISSUE TITLE
How to load scenario file?

### ISSUE THREAD

**Issue by Tom5421** [zoltantamasvajda/openttd-server#4]
Hi, I am trying to load a .scn file and would like to know how this can be achieved with the snap.

**Comment by zoltantamasvajda** [comment]
I can't check right now but you should be able to load it using [rcon](https://wiki.openttd.org/en/Manual/Dedicated%20server#loading-a-game) or by copying the file to `/root/snap/openttd-server/current/.local/share/openttd/save/` and loading it with `sudo snap set openttd-server loadgame=yourscenario.scn`

**Comment by zoltantamasvajda** [comment]
Note: you might need to rename your file from `.scn` to `.sav` for it to work.

**Comment by Tom5421** [comment]
Hey, I have tried this and it doesn't seem to work, any other ideas?

It won't load a regular .sav file, a regular .scn file or a .scn changed to .sav file either.

**Comment by zoltantamasvajda** [comment]
You're most likely missing some newgrfs required. Open the scenario on another computer and download all required newgrfs then copy over your `content_download` and `newgrf` folders to the server and put them into `/snap/openttd-server/current/.local/share/openttd/`. Finally restart the server using `snap restart openttd-server` and try again.

**Comment by Tom5421** [comment]
That has worked, thank you!
